use crate::types::ToolOutput;

pub fn generate_toml_file(command_name: &str, outputs: &[ToolOutput]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Auto-generated tool configuration for: {}\n", command_name));
    out.push_str("# Generated by mcp-tool-generator\n\n");
    
    out.push_str("[config]\n");
    out.push_str("working_dir = \".\"\n\n");

    let mut safe_tools = Vec::new();
    let mut dangerous_tools = Vec::new();

    for o in outputs {
        if o.is_dangerous {
            dangerous_tools.push(o);
        } else {
            safe_tools.push(o);
        }
    }

    if !safe_tools.is_empty() {
        out.push_str("# --- safe tools ---\n\n");
        for t in safe_tools {
            out.push_str(&t.toml_block);
            out.push_str("\n\n");
        }
    }

    if !dangerous_tools.is_empty() {
        out.push_str("# --- dangerous tools (uncomment to enable) ---\n\n");
        for t in dangerous_tools {
            let mut commented = String::new();
            for line in t.toml_block.lines() {
                commented.push_str("# ");
                commented.push_str(line);
                commented.push('\n');
            }
            out.push_str("# DANGEROUS: This command may have side effects\n");
            out.push_str(&commented);
            out.push_str("\n");
        }
    }

    out
}
