use crate::types::ToolOutput;
use mcp::config::tool::ToolFile;

/// 为单个 tool 生成独立的 TOML 文件内容
pub fn generate_single_tool_toml(command_name: &str, output: &ToolOutput) -> String {
    generate_toml_file(command_name, &[output.clone()])
}

pub fn generate_toml_file(command_name: &str, outputs: &[ToolOutput]) -> String {
    let all_defs: Vec<_> = outputs.iter().map(|o| o.tool_def.clone()).collect();

    let tool_file = ToolFile {
        config: None,
        tools: all_defs,
    };

    let mut out = format!(
        "# Auto-generated tool configuration for: {}\n\
         # Generated by mcp-tool-generator\n\n",
        command_name
    );

    let toml_str = toml::to_string_pretty(&tool_file).unwrap();
    out.push_str(&toml_str);
    return out;
}

#[cfg(test)]
mod tests {
    use super::*;
    use mcp::config::tool::{ToolAction, ToolDef};

    fn make_tool(name: &str) -> ToolOutput {
        ToolOutput {
            tool_def: ToolDef {
                name: name.to_string(),
                description: format!("{} description", name),
                action: ToolAction::Command {
                    command: Some("test".to_string()),
                    subcommands: Some(vec![name.to_string()]),
                },
                env: None,
                timeout_secs: None,
                cwd: false,
                parameters: None,
            },
            command: vec!["test".to_string(), name.to_string()],
        }
    }

    #[test]
    fn test_with_parameters_and_arg() {
        use mcp::config::tool::ParameterDef;
        let output = ToolOutput {
            tool_def: ToolDef {
                name: "cargo_build".to_string(),
                description: "Build a cargo project".to_string(),
                action: ToolAction::Command {
                    command: Some("cargo".to_string()),
                    subcommands: Some(vec!["build".to_string()]),
                },
                env: None,
                timeout_secs: None,
                cwd: true,
                parameters: Some(vec![ParameterDef {
                    name: "package".to_string(),
                    description: "Package to build".to_string(),
                    r#type: "string".to_string(),
                    required: false,
                    arg: Some(vec!["-p".to_string()]),
                }]),
            },
            command: vec!["cargo".to_string(), "build".to_string()],
        };
        let toml = generate_toml_file("cargo", &[output]);
        assert!(toml.contains("arg"));
        assert!(toml.contains("-p"));
        assert!(toml.contains("cwd = true"));
        // 验证可解析
        let parsed: ToolFile = toml::from_str(&toml).unwrap();
        assert_eq!(parsed.tools.len(), 1);
        let params = parsed.tools[0].parameters.as_ref().unwrap();
        assert_eq!(params[0].name, "package");
        assert_eq!(params[0].arg.as_ref().unwrap(), &vec!["-p".to_string()]);
    }

    #[test]
    fn test_roundtrip_toml_parse() {
        let outputs = vec![make_tool("status")];
        let toml_str = generate_toml_file("git", &outputs);
        let parsed: ToolFile = toml::from_str(&toml_str).unwrap();
        assert_eq!(parsed.tools[0].name, "status");
        assert!(!parsed.tools[0].cwd);
        assert!(parsed.config.is_none());
    }
}
